common:
  property: common value
some:
  property: common value

spring:
  cloud:
    # org.springframework.cloud.bootstrap.config.PropertySourceBootstrapProperties
    config:
      # allow command line properties & environment variables to take precedence over this config
      override-system-properties: false

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      jmx:
        enabled: false
      graphite:
        enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: "http://localhost:9010/eureka"
